openapi: 3.0.0
info:
  contact:
    name: demo
    email: demo@axway.com
  title: 'Eole Locator api'
  version: '1.0'
  description: 'https://api.eolelocator.com/coupon/ specs'
servers:
  - url: 'http://eolelocator.demo:2002/'
tags:
  - name: eole
  - name: 'locator'
paths:
  /eole:
    get:
      summary: Get parc eolien par pays
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/parceolien'
              examples: {}
      operationId: get-eole-locate
      description: Get parc eolien par pays
    parameters: []
components:
  schemas:
    eolelocatorDateRange:
      title: DateRange
      type: object
      properties:
        start:
          type: string
          x-faker: date.past
        end:
          type: string
          x-faker: date.future
    parceolien:
      title: PARC EOLIEN
      type: object
      x-examples: {}
      properties:
        id:
          type: string
          pattern: '[0-9]{7}'
        code:
          type: string
          enum:
            - SPRINGOFF
            - BACKTOSCHOOL
            - XMASGIFT
            - SUMMERTIME
            - HLLWN
            - MOTHERSDAY
            - FATHERSDAY
            - SWAG_ON
            - JUSTDOIT
        validity:
          $ref: '#/components/schemas/eolelocatorDateRange'
        amount:
          type: string
          enum:
            - 10€
            - 20€
            - 5€
            - 15€
        recipient:
          type: string
          x-faker: internet.email
          format: email
  securitySchemes: {}
  examples: {}
