openapi: 3.0.0
info:
  contact:
    name: demo
    email: demo@axway.com
  title: 'Info watt api'
  version: '1.0'
  description: 'https://api.infowatt.com/coupon/ specs'
servers:
  - url: 'http://infowatt.demo:2001/infowatt'
tags:
  - name: coupon
  - name: 'infowatt'
paths:
  /infowatt:
    get:
      summary: Get Watt Production Informations
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/infowatt'
              examples: {}
      operationId: get-infowatt
      description: Get Watt Production Informations
    parameters: []
components:
  schemas:
    infowattDateRange:
      title: DateRange
      type: object
      properties:
        start:
          type: string
          x-faker: date.past
        end:
          type: string
          x-faker: date.future
    infowatt:
      title: Watt
      type: object
      x-examples: {}
      properties:
        id:
          type: string
          pattern: '[0-9]{7}'
        code:
          type: string
          enum:
            - SPRINGOFF
            - BACKTOSCHOOL
            - XMASGIFT
            - SUMMERTIME
            - HLLWN
            - MOTHERSDAY
            - FATHERSDAY
            - SWAG_ON
            - JUSTDOIT
        validity:
          $ref: '#/components/schemas/infowattDateRange'
        amount:
          type: string
          enum:
            - 10€
            - 20€
            - 5€
            - 15€
        recipient:
          type: string
          x-faker: internet.email
          format: email
  securitySchemes: {}
  examples: {}
